DELIMITER $$

DROP PROCEDURE IF EXISTS `check_table_exists` $$
USE ffbdev$$
CREATE PROCEDURE check_table_exists(IN VAR_TABLE VARCHAR(30))
BEGIN

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = VAR_TABLE;
            
END;$$

DELIMITER ;